***DATA CLEANING***

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import streamlit as st

In [2]:
df= pd.read_csv("data.csv")
df.head()

,Date,Absence_Days,Safe_at_School,Gender,Language,Level,Open_Message,Absence_Pattern,Sleep_Quality,Reasons,Peers_Absent,Teacher_Support,Transport,Easy_Understand
0,"Apr 7, 12:00",3+,إه,ولد,ar,6,NaN,الجمعة,إه,مشكل فالعائلة; مريض; عيان,لا,لا,على رجلي,إه
1,"Apr 7, 11:58",0,إه,بنت,ar,6,NaN,الاتنين,إه,مريض; ماكنفهمش الدروس; خايف; عيان,لا,إيه,على رجلي,لا
2,"Apr 7, 11:57",3+,إه,ولد,ar,6,NaN,مرة مرة وصافي,لا,مشكل فالنقل,إه,إيه,على رجلي,إه
3,"Apr 7, 11:55",3+,إه,ولد,ar,6,شكرا,الاتنين,إه,عيان,إه,إيه,على رجلي,إه
4,"Apr 7, 11:53",3+,لا,ولد,ar,6,كنغيب من اجل الكرة,الجمعة,إه,مريض,إه,إيه,على رجلي,شي مرات

In [3]:
# drop Date, Open message and language columns
df.drop(columns=["Date", "Open_Message", "Language"], inplace=True)
df.head()

,Absence_Days,Safe_at_School,Gender,Level,Absence_Pattern,Sleep_Quality,Reasons,Peers_Absent,Teacher_Support,Transport,Easy_Understand
0,3+,إه,ولد,6,الجمعة,إه,مشكل فالعائلة; مريض; عيان,لا,لا,على رجلي,إه
1,0,إه,بنت,6,الاتنين,إه,مريض; ماكنفهمش الدروس; خايف; عيان,لا,إيه,على رجلي,لا
2,3+,إه,ولد,6,مرة مرة وصافي,لا,مشكل فالنقل,إه,إيه,على رجلي,إه
3,3+,إه,ولد,6,الاتنين,إه,عيان,إه,إيه,على رجلي,إه
4,3+,لا,ولد,6,الجمعة,إه,مريض,إه,إيه,على رجلي,شي مرات

In [4]:
# check for missing values
df.isnull().sum()

Absence_Days       0
Safe_at_School     0
Gender             0
Level              0
Absence_Pattern    0
Sleep_Quality      0
Reasons            0
Peers_Absent       0
Teacher_Support    0
Transport          0
Easy_Understand    0
dtype: int64

In [5]:
df.dtypes

Absence_Days         str
Safe_at_School       str
Gender               str
Level              int64
Absence_Pattern      str
Sleep_Quality        str
Reasons              str
Peers_Absent         str
Teacher_Support      str
Transport            str
Easy_Understand      str
dtype: object

In [6]:
df.columns=['عدد أيام الغياب','آمن من التنمر','الجنس','المستوى الدراسي','نمط الغياب','جودة النوم ','الأسباب','غياب الأقران','الاستدراك','وسيلة النقل','سهولة الفهم']

In [7]:
reason_for_absence =['عيان','مريض','مشكل فالعائلة','ماكنفهمش الدروس','خايف','مشكل فالنقل']

In [8]:
# add new column for reason of absence with 1 in each column detected in reason column and 0 in the others
for reason in reason_for_absence:
    df[reason] = df['الأسباب'].apply(lambda x: 1 if reason in x else 0)
df.head()

,عدد أيام الغياب,آمن من التنمر,الجنس,المستوى الدراسي,نمط الغياب,جودة النوم,الأسباب,غياب الأقران,الاستدراك,وسيلة النقل,سهولة الفهم,عيان,مريض,مشكل فالعائلة,ماكنفهمش الدروس,خايف,مشكل فالنقل
0,3+,إه,ولد,6,الجمعة,إه,مشكل فالعائلة; مريض; عيان,لا,لا,على رجلي,إه,1,1,1,0,0,0
1,0,إه,بنت,6,الاتنين,إه,مريض; ماكنفهمش الدروس; خايف; عيان,لا,إيه,على رجلي,لا,1,1,0,1,1,0
2,3+,إه,ولد,6,مرة مرة وصافي,لا,مشكل فالنقل,إه,إيه,على رجلي,إه,0,0,0,0,0,1
3,3+,إه,ولد,6,الاتنين,إه,عيان,إه,إيه,على رجلي,إه,1,0,0,0,0,0
4,3+,لا,ولد,6,الجمعة,إه,مريض,إه,إيه,على رجلي,شي مرات,0,1,0,0,0,0

In [9]:
# drop the original reason column
df.drop(columns=['الأسباب'], inplace=True)
df.head()

,عدد أيام الغياب,آمن من التنمر,الجنس,المستوى الدراسي,نمط الغياب,جودة النوم,غياب الأقران,الاستدراك,وسيلة النقل,سهولة الفهم,عيان,مريض,مشكل فالعائلة,ماكنفهمش الدروس,خايف,مشكل فالنقل
0,3+,إه,ولد,6,الجمعة,إه,لا,لا,على رجلي,إه,1,1,1,0,0,0
1,0,إه,بنت,6,الاتنين,إه,لا,إيه,على رجلي,لا,1,1,0,1,1,0
2,3+,إه,ولد,6,مرة مرة وصافي,لا,إه,إيه,على رجلي,إه,0,0,0,0,0,1
3,3+,إه,ولد,6,الاتنين,إه,إه,إيه,على رجلي,إه,1,0,0,0,0,0
4,3+,لا,ولد,6,الجمعة,إه,إه,إيه,على رجلي,شي مرات,0,1,0,0,0,0

In [10]:
# same for the transport column
transport_means = ['المشي','النقل']
df['المشي']=df['وسيلة النقل'].apply(lambda x: 1 if 'على رجلي' in x else 0)
df['النقل']=df['وسيلة النقل'].apply(lambda x: 1 if 'النقل' in x else 0)
df.head()

,عدد أيام الغياب,آمن من التنمر,الجنس,المستوى الدراسي,نمط الغياب,جودة النوم,غياب الأقران,الاستدراك,وسيلة النقل,سهولة الفهم,عيان,مريض,مشكل فالعائلة,ماكنفهمش الدروس,خايف,مشكل فالنقل,المشي,النقل
0,3+,إه,ولد,6,الجمعة,إه,لا,لا,على رجلي,إه,1,1,1,0,0,0,1,0
1,0,إه,بنت,6,الاتنين,إه,لا,إيه,على رجلي,لا,1,1,0,1,1,0,1,0
2,3+,إه,ولد,6,مرة مرة وصافي,لا,إه,إيه,على رجلي,إه,0,0,0,0,0,1,1,0
3,3+,إه,ولد,6,الاتنين,إه,إه,إيه,على رجلي,إه,1,0,0,0,0,0,1,0
4,3+,لا,ولد,6,الجمعة,إه,إه,إيه,على رجلي,شي مرات,0,1,0,0,0,0,1,0

In [11]:
# drop the original transport column
df.drop(columns=['وسيلة النقل'], inplace=True)
df.head()

,عدد أيام الغياب,آمن من التنمر,الجنس,المستوى الدراسي,نمط الغياب,جودة النوم,غياب الأقران,الاستدراك,سهولة الفهم,عيان,مريض,مشكل فالعائلة,ماكنفهمش الدروس,خايف,مشكل فالنقل,المشي,النقل
0,3+,إه,ولد,6,الجمعة,إه,لا,لا,إه,1,1,1,0,0,0,1,0
1,0,إه,بنت,6,الاتنين,إه,لا,إيه,لا,1,1,0,1,1,0,1,0
2,3+,إه,ولد,6,مرة مرة وصافي,لا,إه,إيه,إه,0,0,0,0,0,1,1,0
3,3+,إه,ولد,6,الاتنين,إه,إه,إيه,إه,1,0,0,0,0,0,1,0
4,3+,لا,ولد,6,الجمعة,إه,إه,إيه,شي مرات,0,1,0,0,0,0,1,0

In [16]:
# Standardize values

df["عدد أيام الغياب"] = df["عدد أيام الغياب"].replace({
    "0":0, "1-2":1.5, "3+":3
})

df["آمن من التنمر"] = df["آمن من التنمر"].replace({"إه":1, "لا":0})
df['جودة النوم ']  = df['جودة النوم '].replace({"إه":1, "لا":0})
df["الاستدراك"] = df["الاستدراك"].replace({"إيه":1, "لا":0})
df["سهولة الفهم"] = df["سهولة الفهم"].replace({"إه":1, "لا":0,"شي مرات":0.5})
df["غياب الأقران"] = df["غياب الأقران"].replace({"إه":1, "لا":0})
df["الجنس"] = df["الجنس"].replace({"ولد":1, "بنت":0})

In [17]:
df.head()

,عدد أيام الغياب,آمن من التنمر,الجنس,المستوى الدراسي,نمط الغياب,جودة النوم,غياب الأقران,الاستدراك,سهولة الفهم,عيان,مريض,مشكل فالعائلة,ماكنفهمش الدروس,خايف,مشكل فالنقل,المشي,النقل
0,3,1,1,6,الجمعة,1,0,0,1,1,1,1,0,0,0,1,0
1,0,1,0,6,الاتنين,1,0,1,0,1,1,0,1,1,0,1,0
2,3,1,1,6,مرة مرة وصافي,0,1,1,1,0,0,0,0,0,1,1,0
3,3,1,1,6,الاتنين,1,1,1,1,1,0,0,0,0,0,1,0
4,3,0,1,6,الجمعة,1,1,1,0.5,0,1,0,0,0,0,1,0

In [20]:
df.head(10)

,عدد أيام الغياب,آمن من التنمر,الجنس,المستوى الدراسي,جودة النوم,غياب الأقران,الاستدراك,سهولة الفهم,عيان,مريض,مشكل فالعائلة,ماكنفهمش الدروس,خايف,مشكل فالنقل,المشي,النقل
0,3,1,1,6,1,0,0,1,1,1,1,0,0,0,1,0
1,0,1,0,6,1,0,1,0,1,1,0,1,1,0,1,0
2,3,1,1,6,0,1,1,1,0,0,0,0,0,1,1,0
3,3,1,1,6,1,1,1,1,1,0,0,0,0,0,1,0
4,3,0,1,6,1,1,1,0.5,0,1,0,0,0,0,1,0
5,3,1,1,3,1,1,1,1,0,1,1,0,0,0,1,0
6,3,1,0,1,1,1,1,0.5,1,1,0,0,0,0,1,0
7,3,1,0,1,1,1,1,0,0,1,1,1,0,0,1,0
8,3,1,1,5,1,1,0,0,1,1,0,1,0,0,1,0
9,3,0,0,5,1,1,1,0.5,0,1,0,0,0,0,1,0

In [22]:
df.head(33)

,عدد أيام الغياب,آمن من التنمر,الجنس,المستوى الدراسي,جودة النوم,غياب الأقران,الاستدراك,سهولة الفهم,عيان,مريض,مشكل فالعائلة,ماكنفهمش الدروس,خايف,مشكل فالنقل,المشي,النقل
0,3,1,1,6,1,0,0,1,1,1,1,0,0,0,1,0
1,0,1,0,6,1,0,1,0,1,1,0,1,1,0,1,0
2,3,1,1,6,0,1,1,1,0,0,0,0,0,1,1,0
3,3,1,1,6,1,1,1,1,1,0,0,0,0,0,1,0
4,3,0,1,6,1,1,1,0.5,0,1,0,0,0,0,1,0
5,3,1,1,3,1,1,1,1,0,1,1,0,0,0,1,0
6,3,1,0,1,1,1,1,0.5,1,1,0,0,0,0,1,0
7,3,1,0,1,1,1,1,0,0,1,1,1,0,0,1,0
8,3,1,1,5,1,1,0,0,1,1,0,1,0,0,1,0
9,3,0,0,5,1,1,1,0.5,0,1,0,0,0,0,1,0
10,3,1,0,3,1,1,1,0,0,0,1,1,0,0,1,0
11,3,1,0,3,0,1,1,0.5,0,1,0,1,0,0,1,0
12,3,1,1,3,1,1,1,0.5,0,1,0,1,0,0,1,0
13,1.5,1,1,2,1,1,1,1,0,0,1,0,1,0,1,0
14,3,1,"""بنت""",3,0,1,1,0,1,0,1,0,0,1,1,0
15,3,1,ولد,2,1,1,0,0,0,0,0,1,0,0,1,0
16,3,0,بنت,4,0,1,1,0.5,0,0,0,1,0,0,0,1
17,3,1,بنت,4,1,1,1,1,0,0,1,0,0,0,1,0
18,0,1,ولد,4,1,1,1,1,0,0,1,0,0,0,0,1
19,0,1,1,4,1,1,1,1,0,0,1,0,0,0,1,0
20,1.5,0,ولد,4,0,1,1,1,0,1,0,0,0,0,1,0
21,1.5,1,ولد,4,1,0,1,1,0,0,1,0,0,0,1,0
22,1.5,0,بنت,4,0,1,1,0.5,0,1,0,0,0,0,1,0
23,3,1,بنت,4,1,1,0,0,0,0,1,0,0,0,1,0
24,3,1,ولد,4,1,1,0,0.5,0,0,1,0,0,0,1,0
25,3,1,ولد,3,1,1,1,0.5,0,0,0,1,0,0,1,0
26,0,0,بنت,3,0,0,0,0,0,0,0,1,0,0,1,0
27,3,1,بنت,3,1,1,1,0.5,1,0,0,0,0,0,1,0
28,3,1,ولد,6,1,1,1,1,0,1,0,0,0,0,1,0
29,0,1,بنت,6,0,1,1,0.5,0,0,1,0,0,0,1,0
30,3,0,ولد,6,0,1,1,0.5,0,0,1,0,0,0,1,0

In [23]:
#save the cleaned data to a new csv file
df.to_csv("cleaned_data.csv", index=False)